name: Ecommerce
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flutter_inner_drawer: "^0.5.6+1"
  flutter_icons: ^1.1.0
  sliding_up_panel: ^1.0.2
  lottie: ^0.4.1
  search_page:
    git:
      url: git://github.com/Zaouat/search_page.git
  simple_search_bar:
    git: git://github.com/elmissouri16/simples_search_bar.git





dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:


  uses-material-design: true
  fonts:
    - family: Gilory
      fonts:
        - asset: assets/fonts/Gilroy.otf
    - family: GiloryL
      fonts:
        - asset: assets/fonts/GilroyL.otf

  assets:
    - assets/images/cover.jpg
    - assets/images/avatar.jpg
    - assets/like.json
    - assets/images/Vr.jpg




